### ISSUE TITLE
SSO 친구들 블로그 오타 발견

### ISSUE THREAD

**Issue by data-miner00** [GRuuuuu/GRuuuuu.github.io#59]
(한국어 잘 못해서 죄송합니다)
안녕하세요! SSO Friends 블로그에서 오타는 3개 발견했습니다. 

https://github.com/GRuuuuu/GRuuuuu.github.io/blob/510b7a86dae5845f7047f840158f6a14320780d6/_posts/2021-10-08-ssofriends.md?plain=1#L328

`eamil`는 `email`여야 했습니다. 다음에 `OPenId`의 대소문자가 틀렸습니다.

https://github.com/GRuuuuu/GRuuuuu.github.io/blob/510b7a86dae5845f7047f840158f6a14320780d6/_posts/2021-10-08-ssofriends.md?plain=1#L358

마지막 오타는 370번째 줄에 `Athentication` 입니다.

https://github.com/GRuuuuu/GRuuuuu.github.io/blob/510b7a86dae5845f7047f840158f6a14320780d6/_posts/2021-10-08-ssofriends.md?plain=1#L370

아무튼, 기사 너무 재밌게 읽고 많이 배웠습니다. 감사합니다✨

**Comment by GRuuuuu** [comment]
@data-miner00 감사합니다!!! 수정했습니다 😊

**Comment by data-miner00** [comment]
@GRuuuuu 아 그래, 좋아요. 감사합니다😉
